### ISSUE TITLE
Threat/Risk: Providing SMS Hijacker a 2nd piece of the puzzle

### ISSUE THREAD

**Issue by prbsparx** [WebKit/explainers#17]
In many one-time passcode (OTP) sms messages, the string that identifies the service is not a specific host name or domain name, but is a string that the user can recognize as the service that is requesting the OTP.

By implementing this explainer, this could increase the risk inherit to sms-based OTP since the SMS would now contain the host name, and OTP. (Even if base64 encoded as mentioned in another issue)

A real world example of an SMS that would give far more info:
“494771
Use this code for passreset verification”

Based on that info, you get no real information aside from “(my phone number) received an OTP to verify I wanted to reset my password” - but you don’t know on what site. By implementing this explainer you could immediately know the server where I requested a pass reset. (Depending on implementation details)

**Comment by mhardeman** [comment]
I concur that it has this risk, but this information is frequently but not always given up already.  As @prbsparx suggests, some verification messages do go to lengths not to telegraph what site they are associated to.

Regarding further encoding/structure of a message intended NOT to be human readable, there might be an opportunity to include a further data element: a random value which would be an attribute on the particular instance of the input field for the verification value so that the OTP could be bound not only to the origin but further to an instance of a page from that origin which shares the same said random value as an attribute on the page or input field for the OTP response.  Just an idea.  But it would be too much, I think, to try to present in a human readable form.

**Comment by rmondello** [comment]
If a relying party wishes to not reveal where a one-time code is to be used, they can decide to not bind their code to an origin and continue to send whatever style of message they are already sending.

**Comment by mhardeman** [comment]
> If a relying party wishes to not reveal where a one-time code is to be used, they can decide to not bind their code to an origin and continue to send whatever style of message they are already sending.

I agree with that.  Presumably there is still the hurdle of knowing the user's account credentials and it's also quite plausible that the OTP value provided has been bound on the system's backend to a user session key related to the browser session that caused the OTP value to be generated and transmitted.

**Comment by Sam-Hall** [comment]
If site owners wanted insta-login functionality from an SMS OTP code, they would provide it as a URL with a querystring value. The reason we don't do it that way is exactly due to this Threat/Risk. I don't know what proportion of sites include the OTP in a hyperlink, but in my experience, I've never seen it done.

Why not let the OTP prompt page provide details? On the page that generates the SMS, populate an HTTP header or meta tag that contains the SMS Sender ID. We still need to then use a convention for the format of an OTP SMS, but when the OTP code and Sender ID are provided to webkit, it'll know where to populate it.

For cases where Sender ID is not known in advance (perhaps the SMS service uses a pool of numbers), specify a unique value in the body of the SMS and set the HTTP header or meta tag with that same unique value.

E.g.
`SMS From: 1234567890
SMS Body:
Your passcode is: 123456
@9cea3794 #123456`

**Comment by mhardeman** [comment]
I believe that binding to a given page origin and requiring that the candidate page have a field with the attribute tagged to request that the autocomplete OTP be populated in that field is superior.

Regardless of Sender ID, which as you note can be unreliable in many SMS send service scenarios, the OTP autocompletion would only happen where the origin matches and a page is awaiting OTP entry in a field with the appropriate attribute.

Using a chosen nonce, as in your example, might invite particularly bad implementations on the server-side in which a static value is used repeatedly, and that would be far less secure than binding to origin.

**Comment by Sam-Hall** [comment]
Either way, as long as I don't have to put additional details about the service that generates the OTP would I endeavour to use this new functionality.

I'd still feel better about the header option. Seems safer/more efficient, rather than parsing the whole page. Also, it means we have the opportunity to separate the web application from the security appliance. For example, use of an F5 or similar reverse proxy to generate the SMS. It would be able to inject the header without the app needing to worry about it.

Also, I know it's highly unlikely, but what if the SMS arrives before the page fully loads? I'd just prefer it if you use an attribute on the OTP input to find that field when the time comes.

**Comment by hober** [comment]
@mhardeman wrote:

> > I believe that binding to a given page origin and requiring that the
> > candidate page have a field with the attribute tagged to request
> > that the autocomplete OTP be populated in that field is superior.

I agree.

@Sam-Hall replied:

> Also, I know it's highly unlikely, but what if the SMS arrives before
> the page fully loads? I'd just prefer it if you use an attribute on
> the OTP input to find that field when the time comes.

This strikes me as a quality of implementation concern. For instance,
the existing Security Code AutoFill feature of iOS doesn't have this
problem. Codes could be delivered before or after the user has focused
the relevant text field, so implementations need to be cognizant of
that.

**Comment by rmondello** [comment]
I think this discussion of an idea with a different scope than our explainer has run its course. If you have specific suggestions for changes to the explainer, please file new individual issues. Thanks for the feedback, y’all!
