### ISSUE TITLE
Should `controls` be supported for the UA to provide appropriate controls to users?

### ISSUE THREAD

**Issue by Malvoz** [WebKit/explainers#69]
Should `<model>` support the [`controls`](https://html.spec.whatwg.org/multipage/media.html#attr-media-controls) attribute to allow the UA to [expose a user interface to the user](https://html.spec.whatwg.org/multipage/media.html#expose-a-user-interface-to-the-user) similar to `<video>`/`<audio>` (and [MapML `<map>` proposal](https://github.com/Maps4HTML/MapML-Proposal#a-high-level-api))?

The exposed UI may include controls for fullscreen, rotate, volume and zoom.

**Comment by grorg** [comment]
That's what the `interactive` attribute was supposed to be. It's a different name because it isn't actually controls such as for a `video`, although some UAs might actually put UI controls in place. While a model might have some embedded animations, in most cases it will be a static file. The `interactive` attribute would let the user click/tap and drag to rotate the model, for example.

Maybe `controls` is a better name for this. I'll close the issue now but keep a look out for people suggesting the same thing.
